### ISSUE TITLE
Social bar component positioning is inconsistent

### ISSUE THREAD

**Issue by hs14428** [Davospike/segpSPA#10]
On the quiz page, the grey social footer does not sit at the bottom of the page, like intended.

If I format the footer class to have "position: absolute", it does move to the bottom of the page, but when the quiz is submitted and the list of answers are shown, the footer blocks one of the questions and sits in the middle of the page. 

I am trying to get this component to always be right at the bottom of the page, with or without scrolling.

With "position: absolute" in quiz.component.html
![image](https://user-images.githubusercontent.com/57953964/114702621-3643f300-9d1c-11eb-9fd5-85cd30995abd.png)
![image](https://user-images.githubusercontent.com/57953964/114702652-40fe8800-9d1c-11eb-9e4c-dab148f2e87a.png)

**Without** "position: absolute" in quiz.component.html
![image](https://user-images.githubusercontent.com/57953964/114702762-62f80a80-9d1c-11eb-9380-8fcd2c4f2297.png)
![image](https://user-images.githubusercontent.com/57953964/114702791-6c817280-9d1c-11eb-96b7-826f78e304a9.png)

**Comment by hs14428** [comment]
Also, having used the DevTools feature in chrome, I can see that the HTML element is not fully extending down the page without position: absolute. Not sure if this of help
![image](https://user-images.githubusercontent.com/57953964/114703235-edd90500-9d1c-11eb-9477-756e1c61e982.png)

**Comment by marceliwac** [comment]
The thing you are looking for is called 'sticky footer'. It's a somewhat common problem in web development and one you can solve in few different ways. Ultimately, there's more to it than just the `position` property in CSS.

Some ways will require your page to use certain type of display method (i.e. grid, flexbox), so I will let you pick the one that should work in your case. (Here's a link: https://css-tricks.com/couple-takes-sticky-footer/)[https://css-tricks.com/couple-takes-sticky-footer/].

**Comment by marceliwac** [comment]
> Also, having used the DevTools feature in chrome, I can see that the HTML element is not fully extending down the page without position: absolute. Not sure if this of help
> ![image](https://user-images.githubusercontent.com/57953964/114703235-edd90500-9d1c-11eb-9477-756e1c61e982.png)

So what's happening here, is that when you use position absolute, the element to which you apply that property will not be 'enclosed' by its parent (i.e. `<body>` tag), but it will kind of "float" on its own. That will likely be the case with `absolute`, `relative` (in which case, the element space will be displayed where it normally would, but if you move it by for example `bottom: 10px`, the element itself will be displayed 10px higher, but that won't necessarily be reflected in the highlighted space) and `sticky`.

**Comment by hs14428** [comment]
Issue fixed with Marceli's pull request. Thanks
